### ISSUE TITLE
cannot compile on mac os x 10.4

### ISSUE THREAD

**Issue by GoogleCodeExporter** [epylar/s3fs#70]
```
What steps will reproduce the problem?
1. add the following line to s3fs.cpp
#define __off_t off_t
(as described at 
http://mark.aufflick.com/blog/2007/10/28/leopard-amazon-s3-network-
storage)
2. run command:
g++ -Wall -D__FreeBSD__=10 -D_FILE_OFFSET_BITS=64 -I/usr/local/include/fuse 
-L/usr/local/
lib -lfuse -pthread -lcurl -lcrypto `xml2-config --cflags --libs` -ggdb 
s3fs.cpp -o s3fs

What is the expected output? What do you see instead?
expected s3fs to compile, but i get this errors:
i686-apple-darwin8-g++-4.0.1: unrecognized option '-pthread'
s3fs.cpp: In function 'int s3fs_readdir(const char*, void*, int (*)(void*, 
const char*, const stat*, 
off_t), off_t, fuse_file_info*)':
s3fs.cpp:1365: error: 'curl_multi_timeout' was not declared in this scope
s3fs.cpp: At global scope:
s3fs.cpp:441: warning: 'size_t readCallback(void*, size_t, size_t, void*)' 
defined but not used

What version of the product are you using? On what operating system?
s3fs-r177
macfuse-2.0.3
xcode from tiger dvd
mac os x 10.4.9

Please provide any additional information below.
also tried the info at 
http://www.rsaccon.com/2007/10/mount-amazon-s3-on-your-mac.html
it returns the same errors + the following error:
make: pkg-config: Command not found
```

Original issue reported on code.google.com by `bberg1...@gmail.com` on 18 Sep 2009 at 7:58
- Merged into: #106
